import { Booking } from './types';

export const mockBookings: Booking[] = [
  {
    id: '#001',
    clientName: 'Anna Smith',
    email: 'anna.smith@mail.test',
    phone: '+44 7700 100001',
    service: 'Airport Transfer',
    pickup: 'Kensington',
    destination: 'Heathrow T5',
    date: '2026-06-05 08:30',
    status: 'confirmed',
    passengers: 2,
    meetAndGreet: true,
  },
  {
    id: '#002',
    clientName: 'Dmitry Volkov',
    email: 'd.volkov@corp.test',
    phone: '+44 7700 100002',
    service: 'Corporate Transport',
    pickup: 'Canary Wharf',
    destination: 'Liverpool St',
    date: '2026-06-05 09:00',
    status: 'pending',
    company: 'Volkov Enterprises',
    passengers: 1,
  },
  {
    id: '#003',
    clientName: 'Elena Kovalenko',
    email: 'elena.k@test.co.uk',
    phone: '+44 7700 100003',
    service: 'Private Hire',
    pickup: 'Mayfair',
    destination: 'Soho',
    date: '2026-06-05 14:00',
    status: 'confirmed',
    passengers: 3,
  },
  {
    id: '#004',
    clientName: 'Sergey Novikov',
    email: 'novikov@edu.test',
    phone: '+44 7700 100004',
    service: 'Group Transfer',
    pickup: 'Paddington',
    destination: 'Oxford',
    date: '2026-06-06 10:00',
    status: 'pending',
    company: 'Oxford College',
    passengers: 12,
    notes: 'Group of students, need extra luggage space',
  },
  {
    id: '#005',
    clientName: 'Maria West',
    email: 'm.west@mail.test',
    phone: '+44 7700 100005',
    service: 'Airport Transfer',
    pickup: 'Westminster',
    destination: 'Gatwick N',
    date: '2026-06-06 15:30',
    status: 'pending',
    passengers: 1,
    meetAndGreet: true,
  },
  {
    id: '#006',
    clientName: 'Oleg Titov',
    email: 'oleg@event.test',
    phone: '+44 7700 100006',
    service: 'Corporate Transport',
    pickup: 'Beckenham',
    destination: "St Paul's",
    date: '2026-06-07 07:45',
    status: 'confirmed',
    company: 'Event Solutions Ltd',
    passengers: 4,
    notes: 'VIP client, need executive vehicle',
  },
  {
    id: '#007',
    clientName: 'Irina Pavlova',
    email: 'i.pavlova@test.uk',
    phone: '+44 7700 100007',
    service: 'Private Hire',
    pickup: 'Camden',
    destination: 'Heathrow',
    date: '2026-06-08 06:00',
    status: 'pending',
    passengers: 2,
  },
  {
    id: '#008',
    clientName: 'Alexey Morozov',
    email: 'morozov@edu.test',
    phone: '+44 7700 100008',
    service: 'Group Transfer',
    pickup: 'Kingston',
    destination: 'Cambridge',
    date: '2026-06-09 11:00',
    status: 'confirmed',
    company: 'Kingston School',
    passengers: 8,
  },
  {
    id: '#009',
    clientName: 'Natalia Grigorieva',
    email: 'nata@mail.test',
    phone: '+44 7700 100009',
    service: 'Airport Transfer',
    pickup: 'Stratford',
    destination: 'Stansted',
    date: '2026-06-10 12:00',
    status: 'pending',
    passengers: 1,
    meetAndGreet: false,
  },
  {
    id: '#010',
    clientName: 'Vadim Kuznetsov',
    email: 'vk@business.test',
    phone: '+44 7700 100010',
    service: 'Corporate Transport',
    pickup: 'Southbank',
    destination: 'City Airport',
    date: '2026-06-11 16:00',
    status: 'completed',
    company: 'Kuznetsov & Co',
    passengers: 2,
  },
  {
    id: '#011',
    clientName: 'Tatiana Belova',
    email: 't.belova@test.co.uk',
    phone: '+44 7700 100011',
    service: 'Private Hire',
    pickup: 'Greenwich',
    destination: 'Hyde Park',
    date: '2026-06-11 19:00',
    status: 'completed',
    passengers: 4,
    notes: 'Birthday celebration',
  },
  {
    id: '#012',
    clientName: 'Konstantin Romanov',
    email: 'k.romanov@mail.test',
    phone: '+44 7700 100012',
    service: 'Airport Transfer',
    pickup: 'Bloomsbury',
    destination: 'Luton',
    date: '2026-06-12 05:30',
    status: 'pending',
    passengers: 1,
    meetAndGreet: true,
  },
];
